const actionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    RETRIEVE_CART: 'RETRIEVE_CART',
    FILTER_FOR_MEN: 'FILTER_FOR_MEN',
    FILTER_FOR_WOMEN: 'FILTER_FOR_WOMEN',
    FILTER_FOR_KIDS: 'FILTER_FOR_KIDS',
    SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',
    REMOVE_SELECTED_CATEGORY: 'REMOVE_SELECTED_CATEGORY',
}

export default actionTypes