const actionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    RETRIEVE_CART: 'RETRIEVE_CART',
    FILTER_FOR_MEN: 'FILTER_FOR_MEN',
    FILTER_FOR_WOMEN: 'FILTER_FOR_WOMEN',
    FILTER_FOR_KIDS: 'FILTER_FOR_KIDS',
    SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',
    REMOVE_SELECTED_CATEGORY: 'REMOVE_SELECTED_CATEGORY',
    SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    HANDLE_ADD_TO_CART: 'HANDLE_ADD_TO_CART',
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    UPDATE_CART: 'UPDATE_CART',
    SET_CART_EMPTY: 'SET_CART_EMPTY'
}

export default actionTypes